#!/bin/zsh
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run with sudo: sudo ./scripts/setup_borgbar_sudoers.sh"
  exit 1
fi

if [[ -z "${SUDO_USER:-}" ]]; then
  echo "This script must be run via sudo by the target user."
  exit 1
fi

TARGET_USER="$SUDO_USER"
SUDOERS_FILE="/etc/sudoers.d/borgbar-snapshot"

cat > "$SUDOERS_FILE" <<RULES
# BorgBar snapshot commands (generated by setup_borgbar_sudoers.sh)
Cmnd_Alias BORGBAR_SNAPSHOT = /usr/bin/tmutil localsnapshot, /usr/bin/tmutil deletelocalsnapshots *, /sbin/mount_apfs *, /sbin/umount *
$TARGET_USER ALL=(root) NOPASSWD: BORGBAR_SNAPSHOT
RULES

chmod 440 "$SUDOERS_FILE"
/usr/sbin/visudo -cf "$SUDOERS_FILE"

echo "Installed $SUDOERS_FILE for user $TARGET_USER"
